export class Book {
  id;
  title;
  author;
  gender;
  displayed;

  constructor(title: string, author: string, gender: string, displayed: boolean) {
    this.id = this.generateUUID();  
    this.title = title;
    this.author = author;
    this.gender = gender;
    this.displayed = displayed;
  }

  // GPT Prompt: Write a React Native function called generateUUID that returns a 128 hexadecimal string that conforms to version 4 UUID for Apple's Identifiable Protocol.

  // Apple's UUID generator returns a 128 bit hexadecimal string to avoid duplicates
  // Example: 08B15DB4-2F02-4AB8-A965-67A9C90D8A44.
  // General Regex Format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
  // There are some restrictions however:
  // The 4 in the third group indicates that this is a version 4 UUID (randomly generated).
  // The y in the fourth group can be one of 8, 9, A, or B.
  // Essentially mimics the Identifiable protocol in Swift (logic generated by ChatGPT)
  generateUUID() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
      var r = (Math.random() * 16) | 0,
        v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }

  static equals(book1: Book, book2: Book) {
    return book1.title === book2.title && book1.author === book2.author;
  }

  static compare(book1: Book, book2: Book) {
    return book1.title.localeCompare(book2.title);
  }
}
